### ISSUE TITLE
Alternative to wrapping errors

### ISSUE THREAD

**Issue by yangnw** [joyent/node-verror#12]
Wrapping errors feels wrong. How about this:

    // HTTP errors
    err.module = "RFCXXXX"; // or say "HTTP1.1"
    err.code = "XXXX";
    // say registering users
    if (err.code == '23505') { err.module = "RegisterUser"; err.code = "EMAIL_EXISTS"; }
    else { err.module = "PostgreSQL"; }

And the request handler renders appropriately using first err.stand then err.code. Both values can be overwritten.
All you do is provide almost all common error standards like http.STATUS_CODES does, say pg.STATUS_CODES etc.

**Comment by davepacheco** [comment]
Closing this, but feel free to reopen with clarification.
