### ISSUE TITLE
Support for custom error types?

### ISSUE THREAD

**Issue by bjrmatos** [joyent/node-verror#15]
I like the approach of defining custom type errors in this module https://github.com/jayyvis/extend-error , I think it would be great to add this functionality

**Comment by vipreshjha** [comment]
@iliakan  If you have successfully inherited VError can you provide an example .
Cause in the current implementation we get the VError object by calling the method of static class I have not idea how to perform inheritance in this scenario using the inbuilt Node "Util" library.

**Comment by vipreshjha** [comment]
@iliakan  I just checked the docs there is also a constructor function available so I can inherit easily.

**Comment by iliakan** [comment]
oh that was so long ago I can't even remember what the issue was about. There definitely was something. Withdrawing my question cause of lack of memories.

**Comment by yunong** [comment]
@davepacheco Any updates on whether you'll merge in your branch? It'd be really nice to be able to use the new features.

**Comment by davepacheco** [comment]
@yunong I haven't really had a chance to play with it much myself, so I haven't really validated the new design.  Have you tried it?  Or at least looked at the API?

**Comment by shinymayhem** [comment]
@naddison36 That is what I was looking for

**Comment by DonutEspresso** [comment]
Another alternative for folks looking is [https://github.com/restify/errors](restify-errors), we built it on top of VError (thanks Dave!) and made it relatively straightforward to create custom constructors and properties.

**Comment by davepacheco** [comment]
My changes for #10 (which are out for code review) support configuring the "name", and the pattern for inheritance is better documented, too.  Closing this as a dup of #10.  Thanks!
