### ISSUE TITLE
No documentation on how to Install this package

### ISSUE THREAD

**Issue by vipreshjha** [joyent/node-verror#29]
I want to use it in NodeJs. Any help regarding the package name to be used with the npm install command would helpful.

**Comment by vipreshjha** [comment]
Thanks Dave . But it would be really helpful if you include the command in documentation section so that future user might not have to dig the issues to get this info. It may seem to be very trivial thing for you but trust me its really helpful especially when there are plethora of packages out there doing similar stuff and having similar kind of names.

**Comment by davepacheco** [comment]
Done!
