### ISSUE TITLE
1.7 breaking change `we_cause` -> `jse_cause`

### ISSUE THREAD

**Issue by awolden** [joyent/node-verror#37]
A build error was introduced to one of our projects and I tracked it down to this library (via[ restify-errors](https://github.com/restify/errors)).  When receiving an error object back, we were expecting there to be a property called `we_cause`, but it seems that has been mapped to `jse_cause` in the [most recent release](https://github.com/joyent/node-verror/commit/08fa8939cc744dfce40ef1f1b9cad0d454b4b2ce#diff-7b7b65fd47508bd81ac1df9c099cc171L244) . 

This is an easily fixed issue on our end, but I wanted to raise awareness about this potentially breaking change.

Thanks!

**Comment by davepacheco** [comment]
Thanks for the heads-up, and sorry for the impact.  That field was always supposed to be private.  The .cause() method (or, better, the new VError.cause() function) is the expected way to get at that.

**Comment by davepacheco** [comment]
I'm not planning to change this, since restify-errors was depending on a private field.  I'd still like to hear if it's breaking other packages, though.

**Comment by DonutEspresso** [comment]
@awolden restify-errors only uses the internal fields for unit tests (which are indeed currently broken). However, the code itself should not be accessing these fields directly. If you're seeing a problem with restify-errors, please file an issue in our repo. Thanks!

**Comment by awolden** [comment]
@donutespresso Thanks for the response! The issue wasn't with `restify-errors` per-se, our tests were broken cause we were using the same internal properties that probably broke your tests. Based on Dave's comment above we changed our code to use `.cause()` and it's working great. 

We love restify-errors, so if we see an issue we will definitely provide feedback!
