### ISSUE TITLE
want convenience functions for MultiErrors

### ISSUE THREAD

**Issue by davepacheco** [joyent/node-verror#49]
I've found it useful to have a pair of functions for working with MultiErrors:

- `errorForList(list)`: construct a MultiError from the array of errors `list`, but if `list` is empty, returns `null`, and if `list` has only one element, returns that error directly.  In this way, given any number of errors accumulated during an operation, this function returns an appropriate single error to summarize the result.
- `errorForEach(err, func)`: given a normal error, invokes `func(err)`, but given a MultiError, invokes `func(errorN)` for each error underlying the `MultiError`.  I've found this useful for operations that accumulate warnings that may or may not be encapsulated with a MultiError.

**Comment by davepacheco** [comment]
For reviewers interested in seeing these in action:

- errorForList: https://github.com/davepacheco/sdc-manta/blob/dev-RFD-85/lib/alarms/alarms.js#L66-L89
- errorForEach: https://github.com/davepacheco/sdc-manta/blob/dev-RFD-85/cmd/manta-adm.js#L830-L843

**Comment by davepacheco** [comment]
This change is `make prepush` clean on SmartOS 32-bit node v0.10.46.  I don't expect these changes are OS-dependent, data-model-dependent, or version-dependent.

**Comment by paulmelnikow** [comment]
I'm using `errorForList` in [icedfrisby](https://github.com/MarkHerhold/IcedFrisby/pull/53/files). Thanks!

**Comment by davepacheco** [comment]
Cool!
